<?php
	function easyreservations_emailshtml_tutorial(){
		$handler = array('#wpbody a.current', '#idemailselect', '#subj', '#active', '#idplaintext', 'textarea.wp-editor-area', 'td.bar', '#insertag', '#qt_mail1_customs');
		$content = array(
				'<h3>Emails</h3><p>The emails get generated by templates you define below. Each trigger has its own template. The email get send as multipart and contain a HTML and a plain text version of it. You need to set up the HTML version for each template on its own, but you can copy them with <b>CTRL+C</b> &amp; <b>CTRL+V</b>.</p>',
				'<h3>Trigger</h3><p>Select the template you want to edit.</p>',
				'<h3>Subject</h3><p>This will be the subject of the email.</p>',
				'<h3>Active</h3><p>You can de-activate each template on its own.</p>',
				'<h3>Plain/text message</h3><p>The plain/text message is still necessary because of users with old devices that cant read HTML.</p>',
				'<h3>Message</h3><p>This is the message of the email in that you can use the [tags] from the right box to insert the reservations information.</p>',
				'<h3>HTML</h3><p>This is the HTML editor. You can edit your emails with word like functions or switch directly to the HTML version. It comes with three different styles, but you can add your own by adding a .html to </p>',
				'<h3>Tags</h3><p>Use this placeholders to insert the reservations information in the emails. <b>[adminmessage]</b> or <b>[changelog]</b> will only work in related kind of emails.</p>',
				'<h3>Custom and price fields</h3><p>To insert the information from one custom information or price directly you can use <b>[custom title]</b> and <b>[prices title]</b>.</p>',
		);
		$at = array('top', 'top', 'top', 'top', 'top', 'top', 'top', 'top', 'top');

		echo easyreservations_execute_pointer(9, $handler, $content, $at);
	}
?>